SELECT * FROM JPA_EMPLOYEE_DETAILS;

SELECT COMPANY_NAME, LAST_NAME, DEPT_NAME, EMP_MOBILE, BRANCH_NAME, EMP_JOIN_DATE, EMP_END_DATE FROM JPA_EMPLOYEE_DETAILS Where COMPANY_NAME='IBM' and (DEPT_NAME=nvl('IT', DEPT_NAME) or DEPT_NAME='') and (BRANCH_NAME=nvl('BANG', BRANCH_NAME) or BRANCH_NAME='');

SELECT COMPANY_NAME, LAST_NAME, DEPT_NAME, EMP_MOBILE, BRANCH_NAME, EMP_JOIN_DATE, EMP_END_DATE FROM JPA_EMPLOYEE_DETAILS Where EMP_ID = '126' and (DEPT_NAME=nvl('IT', DEPT_NAME) or DEPT_NAME='') and (BRANCH_NAME=nvl('BANG', BRANCH_NAME) or BRANCH_NAME='') and (COMPANY_NAME=nvl('IBM', COMPANY_NAME) or COMPANY_NAME='');

SELECT COMPANY_NAME, LAST_NAME, DEPT_NAME, EMP_MOBILE, BRANCH_NAME, EMP_JOIN_DATE, EMP_END_DATE FROM JPA_EMPLOYEE_DETAILS Where EMP_ID = '125' AND COMPANY_NAME='IBM' and (DEPT_NAME=nvl('IT', DEPT_NAME) or DEPT_NAME='') and (BRANCH_NAME=nvl('BANG', BRANCH_NAME) or BRANCH_NAME='');

SELECT COMPANY_NAME, LAST_NAME,DEPT_NAME, EMP_MOBILE, BRANCH_NAME, EMP_JOIN_DATE, EMP_END_DATE FROM JPA_EMPLOYEE_DETAILS where COMPANY_NAME='IBM' and BRANCH_NAME='BANG' and (DEPT_NAME=nvl('IT', DEPT_NAME) or DEPT_NAME='');



SELECT * FROM jpa_employee_details WHERE company_name = 'IBM';



CREATE TABLE JPA_BRANCH_DETAILS(
BRANCH_CODE VARCHAR2(25) NOT NULL,
BRANCH_NAME VARCHAR2(25) NOT NULL,
PRIMARY KEY(BRANCH_CODE)
);

INSERT INTO JPA_BRANCH_DETAILS VALUES('100', 'IBM');

INSERT INTO JPA_BRANCH_DETAILS VALUES('101', 'VIZ');

INSERT INTO JPA_BRANCH_DETAILS VALUES('102', 'HYD');

INSERT INTO JPA_BRANCH_DETAILS VALUES('103', 'BANG');

SELECT * FROM JPA_BRANCH_DETAILS;


CREATE TABLE JPA_ASSET_DETAILS(
PRD_SOURCE VARCHAR2(50) NOT NULL,
BUSINESS_UNIT_CODE VARCHAR2(50) NOT NULL,
SUPPLIER_ID VARCHAR2(50) NOT NULL,
SUPPLIER_NAME VARCHAR2(50) NOT NULL,
BUYER_ID VARCHAR2(50) NOT NULL,
BUYER_NAME VARCHAR2(50) NOT NULL,
CCY VARCHAR2(50) NOT NULL,
METURITY_DATE VARCHAR2(50) NOT NULL,
INVOICE_NUMBER VARCHAR2(50) NOT NULL,
STATUS VARCHAR2(50) NOT NULL,
INVESTORE_NAME VARCHAR2(50),
ASSET_SUB_TYPE VARCHAR2(50),
FUNDED_INDICATOR VARCHAR2(50),
PROTECTION_ELEMENT VARCHAR2(50),
POLICY_ASSIGNMENT VARCHAR2(50),
PRIMARY KEY(PRD_SOURCE,BUSINESS_UNIT_CODE,CCY)
);

INSERT INTO JPA_ASSET_DETAILS VALUES('REC', 'IBM01','0001', 'UPA','10010', 'IBM','USB', '2019-02-10','0001BC', 'COMPLETED', 'ABC','Y','N','','U');

INSERT INTO JPA_ASSET_DETAILS VALUES('REC', 'IBM01','0001', 'UPA','10011', 'CDE','SUD', '2019-02-10','0001BC', 'COMPLETED', 'ABC','Y','N','','U');

INSERT INTO JPA_ASSET_DETAILS VALUES('REC', 'IBM01','0001', 'UPA','10012', 'PRD','ZED', '2019-02-10','0001BC', 'COMPLETED', 'ABC','Y','N','','U');

INSERT INTO JPA_ASSET_DETAILS VALUES('REC', 'IBM01','0002', 'APA','10012', 'PRD','XYZ', '2019-02-10','0001BC', 'COMPLETED', 'ABC','Y','N','','U');

SELECT * FROM jpa_asset_details;

SELECT PRD_SOURCE,BUSINESS_UNIT_CODE,SUPPLIER_ID, SUPPLIER_NAME,BUYER_ID,BUYER_NAME,CCY,METURITY_DATE,INVOICE_NUMBER,STATUS,INVESTORE_NAME,ASSET_SUB_TYPE,FUNDED_INDICATOR,PROTECTION_ELEMENT,POLICY_ASSIGNMENT FROM jpa_asset_details
WHERE PRD_SOURCE='REC';

COMMIT;



SELECT DISTINCT  SUPPLIER_ID FROM jpa_asset_details ORDER BY SUPPLIER_ID;

















/*
CREATE TABLE COMPANY(
COMP_NAME VARCHAR2(50) NOT NULL,
EMP_LAST_NAME VARCHAR2(50),
DEPT_NAME VARCHAR2(50) NOT NULL,
COMP_MOBILE_NUM VARCHAR2(50),
BRANCH_NAME VARCHAR2(25),
PRIMARY KEY(COMP_NAME,DEPT_NAME)
);

DROP TABLE COMPANY;

INSERT INTO COMPANY VALUES('IBM', 'Madu', 'IT', '8521479632', 'BANG');

SELECT * FROM COMPANY;

CREATE TABLE DEPARTMENT(
DEPT_NAME VARCHAR2(50) NOT NULL,
DEPT_CODE VARCHAR2(50) NOT NULL,
PRIMARY KEY(DEPT_NAME,DEPT_CODE)
);

DROP TABLE DEPARTMENT;

INSERT INTO DEPARTMENT VALUES('IT', 'IT001');

INSERT INTO DEPARTMENT VALUES('Software', 'Software001');

*/