/* Create the EMPLOYEE TABLE*/

CREATE TABLE EMPLOYEE(
EMP_ID VARCHAR2(100),
EMP_NAME VARCHAR2(100),
EMP_COMP_NAME VARCHAR2(100),
EMP_DEPT VARCHAR2(100),
EMP_SALARY NUMBER(38,2),
EMP_GENDER CHAR(1),
EMP_EMAIL VARCHAR2(25),
EMP_MOBILE NUMBER(10),
EMP_ADDRESS VARCHAR(1000),
EMP_JOINDATE DATE,
EMP_ENDDATE DATE
);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A1','RAMESH','CYIENT','IT',30000,'M','ramesh@gmail.com',9642063263,'ECIL KAPRA HYDERABAD',SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A2','KAVITHA','DTDC','ADMIN',20000,'F','kavitha@gmail.com',9652066322,'SECUNDRABAD,HYDERABAD',SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A3','NIRMALA','CYIENT','IT',25000,'F','nirmala@gmail.com',9133572078,'HITECH CITY,HYDERABAD',SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A4','SUDHARSAN','INFOTECH','MANAGER',25000,'F','sudharsan@gmail.com',880182610,'HITECH CITY,HYDERABAD',SYSDATE);

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A5','DEVANSU','HCL','MANAGER',20000,'M','devansu@gmail.com',880182610,'ECIL X ROAD, KAPRA,SAKET,HYDERABAD',SYSDATE);

SELECT * FROM EMPLOYEE;

COMMIT;

SELECT EMP_ID, EMP_NAME, EMP_SALARY FROM EMPLOYEE;

SELECT EMP_ID, SUM(EMP_SALARY) AS TOTAL FROM EMPLOYEE GROUP BY EMP_ID ORDER BY EMP_ID ASC;

UPDATE EMPLOYEE SET EMP_GENDER= 'M' WHERE EMP_NAME = 'SUDHARSAN';

UPDATE EMPLOYEE SET EMP_GENDER= 'M' WHERE EMP_NAME= 'NIRMALA';

UPDATE EMPLOYEE SET EMP_GENDER= 'F' WHERE EMP_NAME = 'NIRMALA';

ALTER TABLE EMPLOYEE ADD (DEPT_CODE NUMBER(30)); 

UPDATE EMPLOYEE SET DEPT_CODE = 10 WHERE EMP_ID = 'A1';

UPDATE EMPLOYEE SET DEPT_CODE = 20 WHERE EMP_ID = 'A2';

UPDATE EMPLOYEE SET DEPT_CODE = 10 WHERE EMP_ID = 'A3';

UPDATE EMPLOYEE SET DEPT_CODE = 30 WHERE EMP_ID = 'A4';

UPDATE EMPLOYEE SET DEPT_CODE = 20 WHERE EMP_ID = 'A5';

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A6','MANASA','HCL','MANAGER',23000,'F','manasa@gmail.com',9133572078,'KESARA,HYDERABAD','20-JAN-2015');

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE,EMP_ENDDATE) VALUES('A8','SAMANTHA','HCL','MANAGER',2300,'F','samantha@gmail.com',9133572078,'KESARA,HYDERABAD','10-FEB-2015','10-MAR-2018');

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE,EMP_ENDDATE) VALUES('A7','JANAKI','INFOTECH','SALSE',2000,'F','janaki@gmail.com',8801826101,'MANIKONDA,HYTECH CITY,HYDERABAD','10-FEB-2012','10-MAY-2017');

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE) VALUES('A9','JANI','HCL','ADMIN',22000,'M','jani@gmail.com',9133572078,'KESARA,HYDERABAD','20-JAN-2015');

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE,EMP_ENDDATE) VALUES('A10','CHIRU','THRINAINA','SALSE',10000,'M','chiru@gmail.com',8801826101,'ECIL,HYDERABAD','10-DEC-2015','10-MAR-2017');

INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_COMP_NAME,EMP_DEPT,EMP_SALARY,EMP_GENDER,EMP_EMAIL,EMP_MOBILE,EMP_ADDRESS,EMP_JOINDATE,EMP_ENDDATE) VALUES('A11','JANAKI','THRINAINA','SALSE',2000,'F','janaki@gmail.com',9632587412,'SECUNDRABAD,HYDERABAD','10-MAR-2012','10-MAY-2017');

SELECT EMP_ID, EMP_NAME, EMP_DEPT, DEPT_CODE, EMP_SALARY FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPT_CODE = 10 WHERE EMP_ID = 'A6';

UPDATE EMPLOYEE SET DEPT_CODE = 20 WHERE EMP_ID = 'A7';

UPDATE EMPLOYEE SET DEPT_CODE = 40 WHERE EMP_ID = 'A8';

UPDATE EMPLOYEE SET DEPT_CODE = 30 WHERE EMP_ID = 'A9';

UPDATE EMPLOYEE SET DEPT_CODE = 50 WHERE EMP_ID = 'A10';

COMMIT;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_ID = 'A6';

COMMIT;

SELECT EMP_NAME, EMP_SALARY FROM EMPLOYEE ORDER BY EMP_SALARY ASC;

SELECT EMP_NAME, EMP_SALARY FROM EMPLOYEE ORDER BY EMP_SALARY DESC;

SELECT COUNT(*) FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD (EMP_ESI NUMBER(8,2));

ALTER TABLE EMPLOYEE ADD (EMP_PF NUMBER(8,2));

UPDATE EMPLOYEE SET EMP_ESI = 200, EMP_PF = 500 WHERE EMP_ID = 'A1';

UPDATE EMPLOYEE SET EMP_ESI = 300, EMP_PF = 100 WHERE EMP_ID = 'A2';

UPDATE EMPLOYEE SET EMP_ESI = 2000, EMP_PF = 500 WHERE EMP_ID = 'A3';

UPDATE EMPLOYEE SET EMP_ESI = 250, EMP_PF = 300 WHERE EMP_ID = 'A4';

UPDATE EMPLOYEE SET EMP_ESI = 600, EMP_PF = 700 WHERE EMP_ID = 'A5';

UPDATE EMPLOYEE SET EMP_ESI = 1000, EMP_PF = 1000 WHERE EMP_ID = 'A6';

UPDATE EMPLOYEE SET EMP_ESI = 250, EMP_PF = 350 WHERE EMP_ID = 'A7';

UPDATE EMPLOYEE SET EMP_ESI = 500, EMP_PF = 1000 WHERE EMP_ID = 'A8';

UPDATE EMPLOYEE SET EMP_ESI = 1000, EMP_PF = 1200 WHERE EMP_ID = 'A9';

UPDATE EMPLOYEE SET EMP_PF = 300 WHERE EMP_ID = 'A10';

COMMIT;

SELECT EMP_ID, EMP_SALARY, EMP_ESI  FROM EMPLOYEE GROUP BY EMP_ID, EMP_SALARY, EMP_ESI;

SELECT EMP_ID, EMP_NAME, EMP_SALARY FROM EMPLOYEE ORDER BY EMP_SALARY DESC;

SELECT SUM(EMP_SALARY) FROM EMPLOYEE;

SELECT MIN(EMP_SALARY) FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

COMMIT;

SELECT EMP_NAME FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_NAME = 'RAMESH' WHERE EMP_ID = 'A9';

/*INTERVIEW QUATION */
/* HOW TO GET THE DUBLICATE NAME FROM THE TABLE */
SELECT EMP_NAME, COUNT(*) FROM EMPLOYEE GROUP BY EMP_NAME HAVING COUNT(*) >1;

/*INTERVIEW QUATION */
/*HOW TO GET THE HIGHT SALARY FROM THE TABLE */
SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

SELECT SUM(EMP_SALARY) FROM EMPLOYEE;

SELECT MIN(EMP_SALARY) FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

/*INTERVIEW QUATION */
/* HOW TO GET THE EMPLOYEE SALARY FROM HIGHT TO LOWYEST */
SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_DEPT, DEPT_CODE FROM EMPLOYEE ORDER BY EMP_SALARY DESC;

/*INTERVIEW QUATION */
/* HOW TO GET THE EMPLOYEE SALARY FROM LOWYEST TO HIGHT */
SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_DEPT, DEPT_CODE FROM EMPLOYEE ORDER BY EMP_SALARY ASC;

COMMIT;

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE;

/*INTERVIEW QUESTION*/
/* HOW TO GET THE EMPLOYEE SALARY FROM HIGHT TO LOWEST */

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE ORDER BY EMP_SALARY DESC;

SELECT EMP_NAME, EMP_SALARY FROM EMPLOYEE ORDER BY EMP_SALARY ASC;

/*INTERVIEW QUESTION*/
/* HOW TO GET THE EMPLOYEE MAXIMUM SALARY OR HIGHT SALARY FROM TABLE */
SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

/* HOW TO GET THE EMPLOYEE MINIMUM SALARY OR LOWEST SALARY FROM TABLE */
SELECT MIN(EMP_SALARY) FROM EMPLOYEE;

/* HOW TO GET THE EMPLOYEE DUBLICATE NAMES FROM THE TABLE*/
SELECT EMP_NAME, COUNT(*) FROM EMPLOYEE GROUP BY EMP_NAME HAVING COUNT(*)>1;

SELECT EMP_NAME, EMP_SALARY FROM EMPLOYEE WHERE EMP_SALARY > 2000 AND EMP_SALARY <20000;

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE;

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE WHERE EMP_DEPT = 'ADMIN' OR EMP_DEPT = 'MANAGER';

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE WHERE EMP_DEPT IN ('ADMIN','MANAGER');

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE WHERE EMP_SALARY <20000 AND EMP_DEPT IN ('ADMIN','IT');

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 25000;

COMMIT;

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

SELECT MIN(EMP_SALARY) FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) FROM EMPLOYEE;

SELECT EMP_NAME, COUNT(*) FROM EMPLOYEE GROUP BY EMP_NAME HAVING COUNT(*)>1;

SELECT EMP_NAME, EMP_SALARY, EMP_DEPT FROM EMPLOYEE ORDER BY EMP_SALARY ASC;

COMMIT;

/*TO FIND THE LIST OF USER IN SYSTEM (ROOT USER)*/
select * from dba_users;

/*TO FIND THE ONE PARTICULAR COLUMN DATA IN SYSTEM (ROOT USER)*/
select username from dba_users;

COMMIT;

DESC USER;


CREATE TABLE USER1(
USERID NUMBER,
USERNAME VARCHAR2(25),
USERPASSWORD VARCHAR2(25),
USERDESIGNATION VARCHAR2(25)
);

DESC USER1;

SELECT * FROM USER1;

TRUNCATE TABLE USER1;

