CREATE TABLE EMPLOYEE(
EMP_ID NUMBER(25),
EMP_NAME VARCHAR2(50),
EMP_SALARY NUMBER(8,2),
EMP_ENDING_DATE DATE,
EMP_DEPT_NAME VARCHAR2(25)
);

DESC EMPLOYEE;

DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
EMP_ID NUMBER(25),
EMP_NAME VARCHAR2(50),
EMP_SALARY NUMBER(8,2),
EMP_JOIN_DATE DATE,
EMP_END_DATE DATE,
EMP_DEPT_NAME VARCHAR(25)
);

DESC EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(10, 'RAMESH',5000.20,'12-JAN-2011',SYSDATE,'MANAGER');

SELECT * FROM EMPLOYEE;

TRUNCATE TABLE EMPLOYEE;

SELECT * FROM EMPLOYEE;

DESC EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(1, 'RAMESH', 50000.25, '10-JAN-11', SYSDATE, 'Sr.Software Engineer');

INSERT INTO EMPLOYEE VALUES(2, 'SAMSUNDHAR', 20000, '1-FEB-2011', SYSDATE, 'CLERK');

INSERT INTO EMPLOYEE VALUES(3, 'NIRMALA', 15000.58, '25-MAR-15', '10-JAN-2018', 'MANAGER');

INSERT INTO EMPLOYEE VALUES(4, 'PANDHU', 10000, '02-MAR-2014', '10-JAN-18', 'CLERK');

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_SALARY, EMP_JOIN_DATE, EMP_DEPT_NAME) VALUES(5, 'JANAKI', 20000.00, SYSDATE, 'SALSE GIRL');

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_SALARY, EMP_JOIN_DATE, EMP_DEPT_NAME) VALUES(6, 'MANASA', 22000, SYSDATE, 'MANAGER');

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_SALARY, EMP_JOIN_DATE, EMP_DEPT_NAME) VALUES(7, 'JANAKI', 22000, '25-DEC-2011', 'ADMIN');

SELECT * FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_SALARY FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_JOIN_DATE, EMP_DEPT_NAME FROM EMPLOYEE;

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_SALARY,EMP_DEPT_NAME) VALUES(8, 'MANIKANTA', 60000, 'ADMIN');

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_SALARY, EMP_DEPT_NAME) VALUES(9, 'BABU',50000, 'MANAGER');

CREATE TABLE DEPARTMENT(
DEPT_ID NUMBER(25),
DEPT_NAME VARCHAR2(25),
DEPT_LOCATION VARCHAR2(25)
);

INSERT INTO DEPARTMENT VALUES(100, 'ADMIN','HYD');

INSERT INTO DEPARTMENT VALUES(101, 'MANAGER', 'HYD');

INSERT INTO DEPARTMENT VALUES(102, 'CLERK', 'BAN');

INSERT INTO DEPARTMENT VALUES(103, 'Sr.MANAGER', 'VIZ');

DESC DEPARTMENT;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE WHERE EMP_ID = 2;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY < 40000;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY > 20000 AND EMP_SALARY <40000;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME = 'ADMIN' AND EMP_SALARY <50000;

SELECT * FROM EMPLOYEE WHERE (EMP_DEPT_NAME = 'ADMIN' OR EMP_DEPT_NAME = 'CLERK') AND EMP_SALARY < 50000;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE >= '1-JAN-2015';

SELECT * FROM EMPLOYEE WHERE EMP_END_DATE < '31-DEC-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE >= '1-JAN-15' AND EMP_END_DATE < '31-DEC-18';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE BETWEEN '1-JAN-15' AND '31-DEC-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER') AND EMP_JOIN_DATE  >= '1-JAN-2015' AND EMP_END_DATE < '31-DEC-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER') AND (EMP_JOIN_DATE BETWEEN '1-JAN-15' AND '31-DEC-18');

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE BETWEEN '1-JAN-2011' AND '31-DEC-2015';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN ('ADMIN','MANAGER') AND EMP_JOIN_DATE  BETWEEN '1-JAN-15' AND '31-DEC-18';

SELECT * FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_DEPT_NAME FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 40000;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 40000 AND 60000;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 10000 AND 25000;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER') AND EMP_JOIN_DATE < '1-DEC-2015';

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 10000 AND 25000 AND EMP_DEPT_NAME IN('ADMIN', 'MANAGER') AND EMP_JOIN_DATE < '1-DEC-15';

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 5000 AND 50000 ;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 15000 AND 25000 AND EMP_JOIN_DATE BETWEEN '1-JAN-11'AND '1-DEC-18' AND EMP_DEPT_NAME = 'ADMIN';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME NOT IN ('ADMIN','MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_SALARY NOT BETWEEN 20000 AND 40000;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN ('ADMIN', 'MANAGER') AND EMP_JOIN_DATE < '1-JAN-16' AND EMP_SALARY BETWEEN 20000 AND 40000 AND EMP_ID NOT BETWEEN 1 AND 5;

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY > 25000 AND EMP_SALARY < 60000;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 25000 AND 60000;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME = 'ADMIN' OR EMP_DEPT_NAME = 'MANAGER';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME = 'ADMIN' AND EMP_SALARY BETWEEN 25000 AND 60000;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN','MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE BETWEEN '1-JAN-2010' AND '31-DEC-2015';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE BETWEEN '1-JAN-10' AND '31-DEC-2015' AND EMP_END_DATE BETWEEN '1-OCT-18' AND '30-OCT-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('CLERK','MANAGER') AND EMP_JOIN_DATE BETWEEN '1-JAN-10' AND '31-DEC-15' AND EMP_END_DATE BETWEEN '1-OCT-18' AND '30-OCT-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('CLERK', 'MANAGER') AND EMP_JOIN_DATE < '30-FEB-11' AND EMP_END_DATE > '1-OCT-18';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE < '25-FEB-11' AND EMP_END_DATE > '20-OCT-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('CLERK', 'MANAGER') AND EMP_JOIN_DATE < '25-FEB-11' AND EMP_END_DATE > '20-OCT-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME != 'CLERK';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME != 'CLERK' AND EMP_DEPT_NAME != 'MANAGER';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME > 'CLERK';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME > 'MANAGER';

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY NOT BETWEEN 15000 AND 25000;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE NOT BETWEEN '1-JAN-11' AND '30-JAN-14';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME NOT IN('CLERK', 'MANAGER', 'ADMIN');

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('MANAGER', 'ADMIN') AND EMP_SALARY BETWEEN 15000 AND 30000 AND EMP_JOIN_DATE BETWEEN '1-JAN-14' AND '30-MAR-18' AND EMP_END_DATE BETWEEN '1-JAN-15' AND '30-DEC-18';

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('MANAGER', 'ADMIN') AND
  EMP_SALARY BETWEEN 15000 AND 30000 AND 
  EMP_JOIN_DATE BETWEEN '1-JAN-14' AND '30-MAR-18' AND
  EMP_END_DATE BETWEEN '1-JAN-15' AND '30-DEC-18';

COMMIT;

SELECT * FROM EMPLOYEE;


/*LIKE OPERATOR*/
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'N%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%A';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%MA%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '_A%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '__R%';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE LIKE '%JAN%';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE LIKE '%15';

SELECT * FROM EMPLOYEE WHERE EMP_SALARY LIKE '_____';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '____';

SELECT * FROM DEPARTMENT;

/*ESCAPE OPERATION EX:'\' 
  LIKE TO FIND THE SOME SYMBOLS B/W NAME 
  LIKE Cheppali_Ramesh here to find this names based on this _ symbol
*/

CREATE TABLE COMPANY(
COMP_ID NUMBER(25),
COMP_NAME VARCHAR2(25),
COMP_LOCATION VARCHAR2(25)
);

INSERT INTO COMPANY VALUES(10,'WIPRO','HYD');

INSERT INTO COMPANY VALUES(11, 'INFOSYS', 'BAN');

INSERT INTO COMPANY VALUES(12,'TECH_MAHENDRA','PUN');

INSERT INTO COMPANY VALUES(11,'INFOSYS', 'HYD');

INSERT INTO COMPANY VALUES(12,'TECH_MAHENDRA','BAN');

INSERT INTO COMPANY VALUES(10,'WIPRO','PUN');

INSERT INTO COMPANY VALUES(13, 'CYIENT%INFOTECH','HYD');

SELECT * FROM COMPANY;

/*USING ESCAPE OPERATOR '\'*/
SELECT * FROM COMPANY WHERE COMP_NAME LIKE '%\%%' ESCAPE '\';

SELECT * FROM COMPANY WHERE COMP_NAME LIKE '%\_%' ESCAPE '\';


/* VVV IMPL INTERVIEW QUATION
TO AVOID THE DUBLICATE FROM THE TABLE AND DISPLAY THE COUNT ALSO
*/
SELECT COMP_ID, COMP_NAME, COUNT(*)  FROM COMPANY GROUP BY COMP_ID, COMP_NAME HAVING COUNT(*) >1;

COMMIT;

/*IS OPERATION*/
SELECT * FROM EMPLOYEE WHERE EMP_END_DATE IS NULL;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE IS NULL AND EMP_END_DATE IS NULL;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE IS NOT NULL;

SELECT * FROM EMPLOYEE WHERE EMP_END_DATE IS NOT NULL;

COMMIT;

SELECT * FROM EMPLOYEE;

/*ALIAS NAMES TO COLUMNS AND TABLES*/
/*COLUMN SYNTAX: SELECT <COLUMN_NAME> AS [ALIAS NAME] FROM <TABLE_NAME> WHERE <CONDITION>*/

SELECT EMP_ID, EMP_NAME, EMP_SALARY*12 AS EMP_ANNUVAL_SALARY FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_SALARY, EMP_DEPT_NAME, EMP_SALARY*12 AS EMP_ANNUVAL_SALARY FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, (SYSDATE-EMP_JOIN_DATE)/365 AS EXPERIENCE FROM EMPLOYEE;

/*TABLE SYNTAX: SELECT <COLUMN_NAMES> FROM <TABLE_NAME> [ALIAS NAME] WHERE <CONDITION> */

SELECT * FROM EMPLOYEE E;

SELECT * FROM DEPARTMENT D;

/* ORDER BY CLAUSE*/
/*SYNTAX: SELECT <COLUMN_NAME> FROM <TABLE_NAME> WHERE <CONDITION> ORDER BY <COLUMN_NAME> [ASC/DESC]*/

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 45000 ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 45000 ORDER BY EMP_SALARY ASC;

SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY ASC; 

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 45000 AND EMP_JOIN_DATE LIKE '%OCT%' ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY > 25000;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY >25000 AND EMP_JOIN_DATE LIKE '%11' AND EMP_END_DATE LIKE '%18';

SELECT * FROM EMPLOYEE WHERE EMP_SALARY > 25000 AND EMP_JOIN_DATE IS NULL;

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE ORDER BY EMP_NAME DESC;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY <25000 ORDER BY EMP_NAME DESC;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY < 25000 ORDER BY EMP_NAME ASC;

SELECT * FROM EMPLOYEE ORDER BY 3 DESC;

SELECT * FROM DEPARTMENT;

/*CREATE THE STUDENT TABLE*/
CREATE TABLE STUDENT(
STD_ID NUMBER(25),
STD_NAME VARCHAR2(25),
STD_MATH NUMBER(25),
STD_PHYS NUMBER(25),
STD_COMP NUMBER(25)
);

INSERT INTO STUDENT VALUES(1,'SAM',80,55,91);
INSERT INTO STUDENT VALUES(2,'MOHAN',35,88,33);
INSERT INTO STUDENT VALUES(3,'RAMESH',35,88,54);
INSERT INTO STUDENT VALUES(4,'SURESH',34,35,58);
INSERT INTO STUDENT VALUES(5,'NAVEEN',75,88,98);
INSERT INTO STUDENT VALUES(6,'NARESH',47,37,42);
INSERT INTO STUDENT VALUES(2,'SUNDHAR',71,32,39);
INSERT INTO STUDENT VALUES(7,'RAMESH',38,98,66);
COMMIT;

SELECT * FROM STUDENT;

/*TO AVOID THE DUBLICATE FROM THE TABLE USING 'DISTINCT' KEY USING*/
/* SELECT DISTINCT <COLUMN_NAMES> FROM TABLE_NAME */
SELECT DISTINCT STD_NAME FROM STUDENT;

SELECT * FROM STUDENT ORDER BY STD_NAME DESC;

SELECT * FROM STUDENT ORDER BY 3 ASC;

SELECT *  FROM DEPARTMENT;

SELECT DISTINCT DEPT_LOCATION FROM DEPARTMENT;

SELECT * FROM DEPARTMENT;

/*CASE STATEMENT*/
SELECT  DEPT_ID, DEPT_NAME, CASE DEPT_ID 
  WHEN 101 THEN 'ADMIN'
  WHEN 102 THEN 'CLERK1'
  ELSE 'UNKNOW'
  END AS DEPT_NAME8 
FROM DEPARTMENT;

/*TO CHECK THE LIST OF TABLES IN DB*/
/*USING TAB*/
/*SYNTAX: SELECT * FROM TAB*/
SELECT * FROM TAB;
  
/*TO FIND THE TOTAL DATABASE NAMES*/
/*SYNTAX: SELECT * FROM GLOBAL-NAME*/


COMMIT;

SELECT * FROM EMPLOYEE;

/*UPDATE COMMANDS*/
/*UPDATE <TABLE_NAME> SET <COLUMN_NAME> = '' <WHERE CONDITION>*/
UPDATE EMPLOYEE SET EMP_JOIN_DATE = '20-JAN-2018' WHERE EMP_NAME = 'MANIKANTA';

UPDATE EMPLOYEE SET EMP_JOIN_DATE = '1-JAN-2017', EMP_END_DATE = '30-OCT-2018' WHERE EMP_ID = 9;

UPDATE EMPLOYEE SET EMP_END_DATE = SYSDATE WHERE EMP_ID = 7;

UPDATE EMPLOYEE SET EMP_END_DATE = '31-OCT18' WHERE EMP_ID = 6;

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE(EMP_ID) VALUES(10);

UPDATE EMPLOYEE SET EMP_NAME = 'RAMARAO', EMP_SALARY = 48000, EMP_DEPT_NAME = 'IT';

/*FLASH BACK*/
/*THIS FLASHBACK USED TO RECOVER THE DATA AFTER COMMIT*/
/*SYNTAX: SELECT * FROM <TABLE_NAME> AS OF TIMESTAMP(SYSDATE-INTERVAL '<MENTIONED_PARTICULAR_TIME>' <MINUTE OR HOURS OR DATS>)*/
SELECT * FROM EMPLOYEE AS OF TIMESTAMP(SYSDATE-INTERVAL '15' MINUTE);

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_SALARY = EMP_SALARY+(EMP_SALARY*0.1);

SELECT * FROM EMPLOYEE AS OF TIMESTAMP(SYSDATE- INTERVAL '10' MINUTE);

COMMIT;

SELECT * FROM EMPLOYEE;

ROLLBACK;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_DEPT_NAME = 'ADMIN' WHERE EMP_ID = 2;

UPDATE EMPLOYEE SET EMP_DEPT_NAME = 'MANAGER' WHERE EMP_ID = 7;

UPDATE EMPLOYEE SET EMP_DEPT_NAME = 'SALSES' WHERE EMP_ID = 4;

UPDATE EMPLOYEE SET EMP_DEPT_NAME = 'ADMIN' WHERE EMP_ID = 5;

UPDATE EMPLOYEE SET EMP_DEPT_NAME = 'SOFTWARE ENGINEER' WHERE EMP_ID = 8;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_JOIN_DATE = SYSDATE WHERE EMP_ID = 10;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER') ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'SALSES') ORDER BY EMP_SALARY ASC;

UPDATE EMPLOYEE SET EMP_SALARY = 25000 WHERE EMP_ID = 1;

UPDATE EMPLOYEE SET EMP_SALARY = 20000 WHERE EMP_ID = 2;

UPDATE EMPLOYEE SET EMP_SALARY = 30000 WHERE EMP_ID = 3;

UPDATE EMPLOYEE SET EMP_SALARY = 15000 WHERE EMP_ID = 4;

UPDATE EMPLOYEE SET EMP_SALARY = 22000 WHERE EMP_ID = 5;

UPDATE EMPLOYEE SET EMP_SALARY = 44000 WHERE EMP_ID = 6;

UPDATE EMPLOYEE SET EMP_SALARY = 21000 WHERE EMP_ID = 7;

UPDATE EMPLOYEE SET EMP_SALARY = 31000 WHERE EMP_ID = 8;

UPDATE EMPLOYEE SET EMP_SALARY = 21000 WHERE EMP_ID = 9;

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 20000 AND 32000 AND EMP_END_DATE IS NOT NULL;

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 30000 AND 55000 AND EMP_END_DATE IS NULL ORDER BY EMP_SALARY DESC;

/*USING ALTER KEY */
ALTER TABLE EMPLOYEE ADD PRIMARY KEY(EMP_ID);

DESC EMPLOYEE;

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_SALARY, EMP_JOIN_DATE, EMP_END_DATE, EMP_DEPT_NAME) VALUES(11,'JANI', 27000 ,'1-JAN-2012',SYSDATE, 'MANAGER');

SELECT EMP_ID, EMP_SALARY, EMP_SALARY*12 AS EMP_ANUVAL_SALARY FROM EMPLOYEE;

/*DISTINCT KEY*/
/*TO AVOID THE DUBLICATE VALUES USING DISTINCT*/
SELECT DISTINCT EMP_DEPT_NAME FROM EMPLOYEE;

COMMIT;


/*ALTER KEY*/
/*ADD COLUMN NATE INTO A TABLE*/
ALTER TABLE EMPLOYEE ADD EMP_COMMISION NUMBER(8,2);

DESC EMPLOYEE;

SELECT * FROM EMPLOYEE;

/*CREATE THE NEW TABLE FROM EXISTING TABLE*/
/*SYNTAX:
  CREATE TABLE <NEW_TABLE_NAME> AS SELECT COLUMNS FORM <OLD_TABLE_NAME>;
*/

CREATE TABLE SUB_EMPLOYEE AS SELECT * FROM EMPLOYEE;

SELECT * FROM SUB_EMPLOYEE;

/*ALTER KEY*/
/*DELETE THE COLUMN NAME FORM TABLE*/
/*SYNTAX:
  ALTER TABLE <TABLE_NAME> DROP COLUMN <COLUMN_NAME>;
*/
ALTER TABLE SUB_EMPLOYEE DROP COLUMN EMP_COMMISION;

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN','MANAGER');

SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 25000 AND 45000;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE BETWEEN '1-JAN-11' AND '31-DEC-2016';
 
SELECT * FROM EMPLOYEE WHERE EMP_END_DATE IS NULL;

SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY ASC;

SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER') ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_ID < 6 ORDER BY EMP_SALARY DESC;

SELECT * FROM EMPLOYEE WHERE EMP_ID > 6 ORDER BY EMP_SALARY ASC;

SELECT EMP_SALARY, EMP_SALARY*12 AS EMP_SALARY_ANNUVAL FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) FROM EMPLOYEE;

SELECT MIN(EMP_SALARY) FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE LIKE '1%';

SELECT * FROM EMPLOYEE WHERE EMP_JOIN_DATE LIKE '%DEC%';

COMMIT;

SELECT * FROM EMPLOYEE;

SELECT DISTINCT EMP_NAME FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_NAME = 'SAMSUNDHAR' WHERE EMP_ID = 5;

UPDATE EMPLOYEE SET EMP_NAME = 'NARESH' WHERE EMP_ID = 6;

UPDATE EMPLOYEE SET EMP_NAME = 'JAN' WHERE EMP_ID = 7;

UPDATE EMPLOYEE SET EMP_NAME = 'NIRMALA' WHERE EMP_ID = 8;

UPDATE EMPLOYEE SET EMP_NAME = 'MAHESH' WHERE EMP_ID = 9;

UPDATE EMPLOYEE SET EMP_NAME = 'PANDU' WHERE EMP_ID = 2;

UPDATE EMPLOYEE SET EMP_NAME = 'AMAR' WHERE EMP_ID = 4;

commit;


/*Create the table form existing table. Here crate the dublicate of same type of Old table
  Here create dublicate table and store the same data from one table to another table.
  Ex.creating replica or dublicate of employee table.
*/
/*SYNTAX*/
  /* 
    CREATE TABLE <NEW_TABLENAME> AS SELECT COLUMNS FROM <OLD_TABLENAME>;
  */
  
CREATE TABLE EMP_DUM1 AS SELECT EMP_NAME, EMP_SALARY FROM EMPLOYEE;

COMMIT;

CREATE TABLE EMP_DUM2 AS SELECT EMP_ID,EMP_DEPT_NAME FROM EMPLOYEE;

SELECT * FROM EMP_DUM2;

CREATE TABLE EMP_DUM3 AS SELECT EMP_ID, EMP_SALARY FROM EMPLOYEE;

SELECT * FROM EMP_DUM3;

CREATE TABLE EMP_DUM4 AS SELECT EMP_ID, EMP_SALARY FROM EMPLOYEE WHERE EMP_SALARY BETWEEN 25000 AND 45000;

SELECT * FROM EMP_DUM4;

CREATE TABLE EMP_DUM5 AS SELECT EMP_ID, EMP_DEPT_NAME FROM EMPLOYEE WHERE EMP_DEPT_NAME IN('ADMIN', 'MANAGER');

SELECT * FROM EMP_DUM5;

UPDATE EMP_DUM5 SET EMP_DEPT_NAME = 'IT' WHERE EMP_ID = 2;

UPDATE EMP_DUM5 SET EMP_DEPT_NAME = 'IT' WHERE EMP_ID = 5;

SELECT * FROM EMP_DUM5;

COMMIT;

CREATE TABLE DEPT_DUM1 AS SELECT * FROM DEPARTMENT; 

SELECT * FROM DEPT_DUM1;

/*DELETE THE DATA FORM TABLE USING TRUNCATE KEY
    TRUNCATE TABLE <TABLE_NAME>;
*/

TRUNCATE TABLE DEPT_DUM1;

SELECT * FROM DEPT_DUM1;

SELECT * FROM DEPARTMENT;

DROP TABLE DEPT_DUM1;

CREATE TABLE DEPT_DUM1 AS SELECT * FROM DEPARTMENT;

COMMIT;

/*FUNCTION
    A FUCTION ACCEPTS SOME INPUTS, PERFOEM SOME CALCULATION AND RETURN SOME VALUES.
    FUNCTIONS ARE 2 TYPES
    1.SINGLE ROW 
    2.MULTIPLE ROW
TYPES OF SINGLE ROWS
1.STRING 
2.MATHEMATICAL
3.DATE
4.CONVERSION
5.SPECIAL
6.ANALYTICAL
*/

/*UPPER() AND LOWER() USING CONVERTS STRING TO UPPERCATE
   SYN:-  UPPER(STRING);
   SYN:-  LOWER(STRING);
*/

/*ORACLE IS PROVIDING ONE DUMMI TABLE. THAT IS DUAL TABLE*/

SELECT UPPER('hello') FROM DUAL;

SELECT LOWER('HELLO') FROM DUAL;

SELECT * FROM EMPLOYEE;

SELECT EMP_ID, LOWER(EMP_NAME) FROM EMPLOYEE;

SELECT EMP_ID, LOWER(EMP_DEPT_NAME) FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE UPPER(EMP_DEPT_NAME) = 'MANAGER';

SELECT LOWER(EMP_NAME) FROM EMPLOYEE WHERE EMP_ID = 2;

COMMIT;

/*INITCAP() USING FOR CONVERTS INITIALS INTO CAPITIALS
  SYN:- INITCAP(STRING);
*/

SELECT INITCAP('sachin tendulkar') FROM DUAL;

SELECT LENGTH('HELLO') FROM DUAL;

SELECT LENGTH('RAMEHS') FROM DUAL;

COMMIT;


SELECT LENGTH('RAMESH') FROM DUAL;

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '_____';

SELECT * FROM EMPLOYEE WHERE LENGTH(EMP_NAME) = 5;


SELECT LENGTH(EMP_NAME) FROM EMPLOYEE;

/** CONVERTING DATE STRING TO DATE FORMATE
*  SYN: TO_DATE(DATE STRING, [FORMAT])
*/

SELECT TO_DATE('1-JAN-17')+INTERVAL '10' DAY FROM DUAL;

SELECT TO_DATE('25-JAN-17')+INTERVAL '15' DAY FROM DUAL;

SELECT TO_DATE('15-JAN-17')-INTERVAL '5' DAY FROM DUAL;

SELECT TO_DATE('1/11/28', 'DD/MM/YY')+10 FROM DUAL;

/* Q) CALCULATE '2017-02-11' + 10 AND DISPLAY OUTPUT IN MM/DD/YY FORMAT **/
/* TO_CAHR()*/

SELECT TO_CHAR(TO_DATE('2017-02-11', 'YYYY-MM-DD')+10, 'MM/DD/YY') DAY FROM DUAL;

COMMIT;

SELECT TO_DATE('11-JAN-18')+INTERVAL '3' DAY FROM DUAL;

SELECT TO_DATE('01/01/15', 'MM/DD/YY')+INTERVAL '2' DAY FROM DUAL;

SELECT TO_DATE('10-FEB-18')+INTERVAL '10' DAY FROM DUAL;

SELECT TO_DATE('02/04/15','MM/DD/YY')+INTERVAL '10' DAY FROM DUAL;

COMMIT;

SELECT TO_DATE('01-MAR-10')+ '20' DAY FROM DUAL;

/*Quasion: Calculate '2017-02-11' + 10 and display output in MM/DD/YY formate?*/
SELECT TO_CHAR(TO_DATE('2017-02-11', 'YYYY-MM-DD')+10, 'MM/DD/YY') FROM DUAL;

SELECT TO_CHAR(TO_DATE('01-FEB-12')-8,'MM/DD/YY') FROM DUAL;

/*CREAT DUMMI TABLE D*/
CREATE TABLE D_DUMMI(D DATE);

INSERT INTO D_DUMMI VALUES(TO_DATE('11-FEB-17 7:40:20', 'DD-MM-YY HH:MI:SS'));

SELECT * FROM D_DUMMI;

CREATE TABLE T_DUMMI(T TIMESTAMP);

INSERT INTO T_DUMMI VALUES('10-JAN-17 2:12:14');

INSERT INTO T_DUMMI VALUES('12-JAN-14 12:45:32');

INSERT INTO T_DUMMI VALUES('13-FEB-12 11:01:23');

SELECT * FROM T_DUMMI;

SELECT * FROM EMPLOYEE;

/*TO DISPALY THE SALARY IN $ FORMATE*/
SELECT EMP_NAME, TO_CHAR(EMP_SALARY, 'L9,999,99') AS SALARY FROM EMPLOYEE;

/*TO_NUMBER() METHOD TO CONVERT NUMERIC STRING TO NUMBER*/
SELECT 1000+TO_NUMBER('1,000','9,999') FROM DUAL;

SELECT 300+TO_NUMBER('2000','99999') FROM DUAL;

SELECT 200-TO_NUMBER('3000','9999') FROM DUAL;

SELECT TO_NUMBER('2500', '9999')-300 FROM DUAL;

COMMIT;
















